nginx:
  namespace: nginx
  upstreamUrl: "wpapp.wpapp.svc.cluster.local"
  upstreamPort: 80
  replicas: 2
  image:
    repository: nginx
    tag: "1.19.10"
  service:
    type: NodePort
    port: 80

